---
- name: Run common tasks
  include: common.yml

- name: Run development tasks
  include: development/main.yml
  when: vm == 1

- name: Run production tasks
  include: production/main.yml
  when: vm == 0
